# Generated by Django 5.2.1 on 2025-05-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_adreses_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adreses',
            new_name='adress',
        ),
    ]
