# Generated by Django 5.2.1 on 2025-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_adreses_student_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
