# Generated by Django 5.2.1 on 2025-05-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_birthday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_heart_problems', models.BooleanField(default=False)),
                ('has_joint_pain', models.BooleanField(default=False)),
                ('takes_medication', models.BooleanField(default=False)),
                ('had_surgeries', models.BooleanField(default=False)),
                ('smokes', models.BooleanField(default=False)),
                ('drinks_alcohol', models.BooleanField(default=False)),
                ('practices_physical_activity', models.BooleanField(default=False)),
                ('physical_activity_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_goals', models.TextField(blank=True)),
                ('medical_restrictions', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='users.student')),
            ],
        ),
    ]
