# Generated by Django 5.2.1 on 2025-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='drinks_alcohol',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='fitness_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='had_surgeries',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='has_heart_problems',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='has_joint_pain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='practices_physical_activity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='smokes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='takes_medication',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
