# Generated by Django 5.2.1 on 2025-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_adress_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='fitness_goals',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_restrictions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='physical_activity_frequency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
